name: Upload Odroid Binary to FirmwareCI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  upload-odroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to FirmwareCI
        uses: docker://firmwareci/action:v5.2
        with:
          TOKEN: ${{ secrets.FWCI_TOKEN }}
          WORKFLOW_NAME: Odroid-H4-Board
          BINARIES: Binary=.github/assets/odroid-h4.bin
